version: '3.9'

services:

  backend:
    build:
      context: ./TicTacToe_Backend
      dockerfile: TicTacToeDockerfile
    container_name: backend
    environment:
      - ASPNETCORE_URLS=value
      - ASPNETCORE_HTTPS_PORT = "443"
      - ASPNETCORE_Kestrel__Certificates__Default__Path= "/https/aspnetapp.pfx"
      - ASPNETCORE_Kestrel__Certificates__Default__Password= "password12345"
      - RabbitMqConfig__Username=tictactoe
      - RabbitMqConfig__Password=Passw0rd
      - RabbitMqConfig__Hostname=rabbitmq
      - DB__Postgres__ConnectionString="User Id=postgres;Password=P@ssw0rd;Server=postgres;Port=5433;Database=TicTacToe;"
      - DB__Mongo__ConnectionString="mongodb://localhost:27017"
    ports:
      - "80:80"
      - "81:443"
    depends_on:
      - postgres
      - mongo

"DB": {
    "Mongo": {
      "ConnectionString": "mongodb://localhost:27017",
      "DatabaseName": "test",
      "CollectionName": "users"
    },
    "Postgres": {
      "ConnectionString": "User Id=postgres;Password=P@ssw0rd;Server=localhost;Port=5433;Database=TicTacToe;"
    }
  },


  frontend:
    build: 
      context: ./tic-tac-toe-front
      dockerfile: FrontDockerfile
    container_name: frontend
    environment:
      - HOST="https://localhost:81"
      - GAMEHUB="https://localhost:81/game-hub"
    ports:
      - "3000:3000"
      
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: TicTacToe
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "P@ssw0rd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5433:5432"

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "tictactoe"
      RABBITMQ_DEFAULT_PASS: "Passw0rd"